name: gitmerge

on:
  push:
    branches:
    - main
    - dev/test
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        if [ -f requirements_dev.txt ]; then
          pip install -r requirements_dev.txt
        fi

    - name: Run unit tests and generate coverage report
      run: |
        python -m unittest -v
        coverage run -m unittest
        coverage report
        coverage html

    - name: Upload code coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: htmlcov

    - name: Package creation
      run: |
        python -m pip install --user --upgrade build
        python -m build

    - name: Archive package
      uses: actions/upload-artifact@v2
      with:
        name: gitmerge
        path: dist
  
  autopep8:
    name: autopep8
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: autopep8
      uses: peter-evans/autopep8@v1
      with:
        args: --global-config .pep8 .

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: autopep8 action fixes
        title: Fixes by autopep8 action
        body: This is an auto-generated PR with fixes by autopep8.
        labels: autopep8, automated pr
        reviewers: bensch98
        branch: autopep8-patches
    
    - name: Fail if autopep8 made changes
      if: steps.autopep8.outputs.exit-code == 2
      run: exit 1
