name: gitmerge

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        if [ -f requirements_dev.txt ]; then
          pip install -r requirements_dev.txt
        fi

    - name: Run unit tests and generate coverage report
      run: |
        python -m unittest -v
        coverage run -m unittest
        coverage report
        coverage html

    - name: Upload code coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: htmlcov

    - name: Package creation
      run: |
        python -m pip install --user --upgrade build
        python -m build

    - name: Archive package
      uses: actions/upload-artifact@v2
      with:
        name: gitmerge
        path: dist
  
  autopep8:
    name: autopep8
    needs: build
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: $${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}

    - name: autopep8
      id: autopep8
      uses: peter-evans/autopep8@v1
      with:
        args: --global-config .pep8 .

    - name: Commit autopep8 changes
      if: steps.autopep8.outputs.exit-code == 2
      run: |
        git config --global user.name 'bensch98'
        git config --global user.email 'scheffler.benedikt@googlemail.com'
        git add .
        git commit -m 'automated autopep8 fixes'
        git push
